import { ArrowRight, CalendarDays, Clock3, MapPin, Phone, ShieldCheck, Sparkles, Star } from "lucide-react";
import type { SiteConfig } from "@/lib/site-config";
import { FaqAccordion } from "@/lib/ui/accordion";

export const meta = { industry: "dental", label: "Family & cosmetic dentistry", accent: "#09a7a1" };
export const sampleConfig: SiteConfig = {
  business: { name: "Cove Dental Studio", category: "Family & cosmetic dentistry", phone: "(905) 555-0182", tel: "tel:+19055550182", address: "185 Main Street South, Brampton, ON L6Y 1N2", mapsUrl: "https://maps.google.com", area: "Brampton, ON", rating: 4.9, reviewCount: 328, hours: [{ day: "Mon – Thu", value: "8:00 AM – 7:00 PM" }, { day: "Friday", value: "8:00 AM – 4:00 PM" }, { day: "Saturday", value: "By appointment" }] },
  copy: { heroHeadline: "A healthier smile starts here.", heroSub: "Modern dentistry with a gentle touch, thoughtful technology, and a care plan built around you.", about: "We created Cove to make dental care feel more personal. From the first hello to every follow-up, our team explains what matters, listens closely, and keeps your comfort at the centre of the experience.", services: [{ title: "General dentistry", desc: "Prevention, exams, and everyday care for a healthy foundation." }, { title: "Cosmetic dentistry", desc: "Whitening, bonding, and smile design that still looks like you." }, { title: "Dental implants", desc: "A durable, natural-looking answer for missing teeth." }, { title: "Clear aligners", desc: "A discreet route toward a more confident bite." }, { title: "Family dentistry", desc: "Gentle care that makes every generation feel welcome." }, { title: "Emergency visits", desc: "Prompt, reassuring help when you need it most." }], faq: [{ q: "Are you accepting new patients?", a: "Yes. We welcome new patients and make the first visit simple, unhurried, and clear." }, { q: "Do you offer direct insurance billing?", a: "Our team can help you understand your coverage and submit eligible claims directly." }, { q: "What if I have dental anxiety?", a: "You are not alone. We take time, explain each step, and tailor your visit around your comfort." }] },
  reviews: [{ author: "Sofia M.", rating: 5, text: "The calmest dental visit I have ever had. Every person was kind and incredibly thorough.", relativeTime: "2 weeks ago" }, { author: "Daniel K.", rating: 5, text: "Beautiful space, practical advice, and a team that actually listens.", relativeTime: "1 month ago" }, { author: "Priya R.", rating: 5, text: "My kids were relaxed from the first appointment. That says everything.", relativeTime: "3 months ago" }],
  gallery: [{ caption: "Comfort-first appointments" }, { caption: "Digital smile planning" }, { caption: "Care for every generation" }], booking: { enabled: true, label: "Book an appointment", url: "https://bookme-web.onrender.com/" }, primaryCta: { label: "Book an appointment", href: "#booking" },
};

export default function SiteTemplate({ config }: { config: SiteConfig }) {
  const { business, copy, reviews, booking, gallery } = config; const services = copy.services ?? [];
  return <main className="min-h-screen overflow-hidden bg-[#f8feff] font-sans text-[#082b4f]">
    <header className="relative z-10 border-b border-[#d5f4f4] bg-white"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4 lg:px-10"><a href="#top" className="flex items-center gap-2 font-display text-xl font-bold"><span className="grid size-10 place-items-center rounded-xl bg-[#08a7a1] text-white"><ShieldCheck className="size-6" /></span>{business.name}</a><div className="flex items-center gap-4"><a href={business.tel} className="hidden text-sm font-semibold md:block">{business.phone}</a><a href="#booking" className="rounded-xl bg-[#ff5a19] px-4 py-3 text-sm font-bold text-white shadow-lg shadow-orange-200">{booking?.label || "Book now"}<ArrowRight className="ml-2 inline size-4" /></a></div></div></header>
    <section id="top" className="relative isolate overflow-hidden bg-[#dffaff]"><div className="absolute inset-0 -z-10 bg-[radial-gradient(circle_at_75%_45%,#06b8e9_0,transparent_20%),radial-gradient(circle_at_78%_45%,#0a77d8_0,transparent_38%),linear-gradient(115deg,#eaffff_0%,#c9f5ff_50%,#f8feff_100%)]" /><div className="mx-auto grid max-w-7xl items-center gap-8 px-5 py-16 lg:grid-cols-[1fr_.9fr] lg:px-10 lg:py-24"><div><p className="text-xs font-bold uppercase tracking-[.22em] text-[#079f9d]">Modern care. Made human.</p><h1 className="mt-5 max-w-2xl font-display text-5xl font-bold leading-[.92] tracking-[-.06em] sm:text-7xl">{copy.heroHeadline}</h1><p className="mt-6 max-w-xl text-lg leading-8 text-[#315a75]">{copy.heroSub}</p><div className="mt-8 flex flex-wrap gap-3"><a href="#booking" className="rounded-xl bg-[#08a7a1] px-6 py-4 text-sm font-bold text-white">{booking?.label || "Book now"}<CalendarDays className="ml-2 inline size-4" /></a><a href="#services" className="rounded-xl border border-[#08a7a1]/30 bg-white/70 px-6 py-4 text-sm font-bold">Explore our care</a></div><div className="mt-9 flex flex-wrap gap-5 text-sm font-semibold text-[#315a75]"><span><Star className="mr-1 inline size-4 fill-[#f5b82e] text-[#f5b82e]" />{business.rating} rating</span><span><ShieldCheck className="mr-1 inline size-4 text-[#08a7a1]" />Direct billing</span></div></div><div className="relative mx-auto aspect-square w-full max-w-md"><div className="absolute inset-0 rounded-[3rem] bg-[#0d80d9] shadow-2xl shadow-cyan-300/70" /><div className="absolute inset-7 rounded-[2.3rem] border border-white/40 bg-[radial-gradient(circle_at_40%_25%,#efffff_0,#aeeaff_22%,transparent_23%),linear-gradient(145deg,#1ac4dd,#0965c9)]" /><ShieldCheck className="absolute left-1/2 top-1/2 size-52 -translate-x-1/2 -translate-y-1/2 fill-white text-white drop-shadow-[0_18px_20px_rgba(0,45,120,.28)] sm:size-64" /><div className="absolute -bottom-5 -left-5 rounded-2xl bg-white p-5 shadow-xl"><p className="text-3xl font-bold text-[#08a7a1]">{business.reviewCount}+</p><p className="text-xs font-semibold text-slate-500">happy patients</p></div></div></div></section>
    <section className="relative z-10 mx-auto -mt-1 max-w-7xl px-5 lg:px-10"><div className="grid overflow-hidden rounded-b-2xl bg-[#082b4f] text-white md:grid-cols-3">{[[Clock3,"Open today",business.hours?.[0]?.value],[CalendarDays,"New patients","Easy first visits"],[Phone,"Need urgent care?",business.phone]].map(([Icon,title,detail]) => <div key={String(title)} className="flex items-center gap-4 border-white/15 p-6 md:border-r last:border-0"><Icon className="size-8 text-[#4fe5da]" /><div><p className="font-display text-lg font-bold">{title}</p><p className="text-sm text-white/70">{detail}</p></div></div>)}</div></section>
    <section id="services" className="mx-auto max-w-7xl px-5 py-20 lg:px-10"><div className="text-center"><p className="text-xs font-bold uppercase tracking-[.22em] text-[#08a7a1]">Our services</p><h2 className="mt-3 font-display text-4xl font-bold tracking-tight">Complete dental care, close to home.</h2></div><div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{services.map((service,index) => <article key={service.title} className="group rounded-2xl border border-[#d7eff2] bg-white p-7 shadow-sm transition hover:-translate-y-1 hover:shadow-xl"><span className="grid size-12 place-items-center rounded-xl bg-[#e2fbfa] font-display font-bold text-[#08a7a1]">0{index+1}</span><h3 className="mt-8 font-display text-xl font-bold">{service.title}</h3><p className="mt-3 text-sm leading-6 text-slate-500">{service.desc}</p><span className="mt-6 inline-block text-sm font-bold text-[#08a7a1]">Learn more <ArrowRight className="inline size-4" /></span></article>)}</div></section>
    <section id="booking" className="bg-[#082b4f] px-5 py-20 text-white lg:px-10"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-2"><div><p className="text-xs font-bold uppercase tracking-[.22em] text-[#4fe5da]">Your first visit</p><h2 className="mt-4 font-display text-5xl font-bold tracking-tight">Feel looked after from the start.</h2><p className="mt-5 max-w-lg text-lg leading-8 text-white/70">A welcoming team, clear answers, and a plan for a healthier smile—without the pressure.</p>{reviews.slice(0,1).map(review => <blockquote key={review.author} className="mt-10 border-l-2 border-[#4fe5da] pl-5 text-lg italic text-white/85">“{review.text}”<footer className="mt-3 text-sm not-italic font-bold">— {review.author}</footer></blockquote>)}</div><div className="rounded-3xl bg-white p-7 text-[#082b4f] shadow-2xl"><div className="flex items-center gap-3"><span className="grid size-12 place-items-center rounded-full bg-[#e2fbfa] text-[#08a7a1]"><CalendarDays /></span><div><p className="font-display text-xl font-bold">Reserve your visit</p><p className="text-sm text-slate-500">Choose a time that works for you.</p></div></div><div className="mt-7 grid gap-3 sm:grid-cols-2">{["Your name","Phone number","Email address","Preferred day"].map(label => <div key={label} className="rounded-xl border border-slate-200 px-4 py-3 text-sm text-slate-400">{label}</div>)}</div><div className="mt-3 rounded-xl border border-slate-200 px-4 py-3 text-sm text-slate-400">What can we help with?</div><a href={booking?.url} target="_blank" rel="noopener noreferrer" className="mt-5 block rounded-xl bg-[#ff5a19] px-5 py-4 text-center text-sm font-bold text-white">{booking?.label || "Book an appointment"}<ArrowRight className="ml-2 inline size-4" /></a><p className="mt-4 text-center text-xs text-slate-400">Your information is private and secure.</p></div></div></section>
    <section className="mx-auto grid max-w-7xl gap-10 px-5 py-20 lg:grid-cols-[.9fr_1.1fr] lg:px-10"><div className="rounded-3xl bg-[#dffaff] p-8"><Sparkles className="size-9 text-[#08a7a1]" /><h2 className="mt-8 font-display text-4xl font-bold">Care with a calming difference.</h2><p className="mt-5 leading-7 text-[#315a75]">{copy.about}</p><a href={business.mapsUrl} className="mt-8 inline-flex items-center gap-2 text-sm font-bold text-[#08a7a1]"><MapPin className="size-4" />{business.address}</a></div><div>{gallery?.map((item,index) => <div key={item.caption} className="mb-3 flex min-h-24 items-end rounded-2xl bg-gradient-to-r from-[#0b6ac5] via-[#15bcd5] to-[#b8f6f3] p-6 text-xl font-display font-bold text-white" style={{opacity:1-index*.13}}>{item.caption}</div>)}<FaqAccordion items={copy.faq} className="mt-8" /></div></section>
    <footer className="bg-[#061e38] px-5 py-10 text-white lg:px-10"><div className="mx-auto flex max-w-7xl flex-wrap justify-between gap-4"><p className="font-display text-xl font-bold">{business.name}</p><a href={business.tel}>{business.phone}</a><span>{business.area}</span></div></footer>
  </main>;
}
